var products1 = [
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"01.jpg",
		bigImage:0,
		index:0
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"02.jpg",
		bigImage:0,
		index:1
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"03.jpg",
		bigImage:0,
		index:2
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"04.jpg",
		bigImage:0,
		index:3
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"05.jpg",
		bigImage:0,
		index:4
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"06.jpg",
		bigImage:0,
		index:5
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"07.jpg",
		bigImage:0,
		index:6
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"08.jpg",
		bigImage:0,
		index:7
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"09.jpg",
		bigImage:0,
		index:8
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"10.jpg",
		bigImage:0,
		index:9
	},
	{
		photographer:"Michelle",
		path:"images/zuopin2017/student/",
		coutry:"Gentile",
		category:"",
		rank:"Shortlisted",
		smallImage:"11.jpg",
		bigImage:0,
		index:10
	},


];
